/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

// Project Euler Solution
function fib(n) {
    let a = 1;
    let b = 1;
    let sum = 0;

    while (b <= n) {
        if (b % 2 === 0) {
            sum += b;
        }
        [a,b] = [b, a + b];
    }
    return sum;
}

console.log(fib(4000000));

// HackerRank Solution
/*function main() {
    var t = parseInt(readLine());
    for(var a0 = 0; a0 < t; a0++){
        var n = BigInt(readLine()); // change this line to parse to BigInt
    console.log(fib2(n).toString());
    }
}*/

function fib2(n) {
    let a = 1n;
    let b = 1n;
    let sum = 0n;

    while (b <= n) {
        if (b % 2n === 0n) {
            sum += b;
        }
        [a,b] = [b, a + b];
    }
    return sum;
}

console.log(fib2(4000000).toString());